In [1]:
import tensorflow as tf

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [2]:
tf.__version__

'2.20.0'

# 1. tf.constant()

1. Create a constant(scaler)

In [5]:
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

2. ndim 

In [6]:
scaler.ndim

0

3. Create a vector

In [7]:
vector = tf.constant([10,20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [8]:
vector.ndim

1

4. Matrix

In [9]:
matrix = tf.constant([[1,2],
                      [3,4]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]])
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float32)>

5. Tensor

In [12]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                        [[13,14,15],
                         [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim

3

- Scaler: a single number
- Vector: a number with direction
- Matrix: a 2-dimensional array of numbers
- Tensor: an n-dimensional array of numbers 

# 2. tf.variable()

In [15]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try to change one of the elements in our changeable tensor
changeable_tensor[0] = 7
# TypeError: 'ResourceVariable' object does not support item assignment

TypeError: 'ResourceVariable' object does not support item assignment

In [17]:
# How about we try .assign()
changeable_tensor[0].assign(8)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([8, 7], dtype=int32)>

In [ ]:
# Let's try change our unchangeable_tensor
unchangeable_tensor[0] = 7
# TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [ ]:
# How about we try .assign()
unchangeable_tensor[0].assign(8)
# AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# 3. Creating Random Tensors

In [24]:
# create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42)  # for reproducibility
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# 4. Shuffling the Order of Tensors
for randomization in data

In [25]:
# Shuffle a tensor 
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])

not_shuffled.ndim

2

In [26]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [27]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
# 1. Must set the both seeds while shuffling
tf.random.set_seed(42) # global level
tf.random.shuffle(not_shuffled, seed=42) # operation level


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. 


# 5. Creating Tensors from Numpy Array

In [55]:
# tf.ones(), tf.zeros(), 

# Trun numpy arrays into tensors
# The main difference between Numpy arrays and Tensorflow tensors is that tensors can be run on a GPU (much faster for computing). Otherwise they are very similar.

import numpy as np 
numpy_A = np.arange(1,25, dtype=np.int32) 
numpy_A

# X = tf.constant(some_matrix) # capital for Matrix
# y = tf.constant(vector) # lowercase for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [56]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [58]:
A = tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

# 6. Tensor Attributes

In [59]:
# shape, rank, axis, and size


# 7. Indexing and Expanding Tensors

In [60]:
# Tensors can be indexed just like Python lists. 

rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [62]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [64]:
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [66]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [67]:
# Alternative
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [68]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

# 8. Manipulating Tensors 
Tensor operations

In [69]:
# Scaler operations
# Vector Operations
# Matrix Multiplication
# http://matrixmultiplication.xyz/

# tf.linalg.matmul
# matrix multiplication with @ operator

In [71]:
tensor = tf.constant([[10,7],
                      [3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [72]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [75]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [76]:
tensor * tensor # dot product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [79]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

Y = tf.constant([[7, 8],
                 [9,10],
                 [11,12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [80]:
print("Normal Y: ", Y)

print("Y reshaped to (2,3):")
print(tf.reshape(Y, (2,3)))

print("Y transposed: ")
print(tf.transpose(Y))

Normal Y:  tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


# 9. Change the datatype of tensor

In [81]:
# dtype, tf.cast()

# 10. Finding the min, max, mean, sum (aggregation)
You can quickly aggregate (perform a calculation on a whole tensor) tensors to find things like the minimum value, maximum value, mean and sum of all the elements.

To do so, aggregation methods typically have the syntax reduce()_[action], such as:

- tf.reduce_min() - find the minimum value in a tensor.
- tf.reduce_max() - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
- tf.reduce_mean() - find the mean of all elements in a tensor.
- tf.reduce_sum() - find the sum of all elements in a tensor.

> Note: typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().

# 11. Finding the positional maximum and minimum
How about finding the position a tensor where the maximum value occurs?

- This is helpful when you want to line up your labels (say ['Green', 'Blue', 'Red']) with your prediction probabilities tensor (e.g. [0.98, 0.01, 0.01]).
- In this case, the predicted label (the one with the highest prediction probability) would be 'Green'.
- You can do the same for the minimum (if required) with the following:
    - tf.argmax() - find the position of the maximum element in a given tensor.
    - tf.argmin() - find the position of the minimum element in a given tensor.

# 12. One-hot encoding
- If you have a tensor of indicies and would like to one-hot encode it, you can use tf.one_hot().
- You should also specify the depth parameter (the level which you want to one-hot encode to).

In [86]:

# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [87]:
# Specify custom values for on and off encoding
tf.one_hot(some_list, depth=4, on_value="We're live!", off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're live!", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're live!", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're live!", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're live!"]], dtype=object)>

# 13. Using @tf.function

In your TensorFlow adventures, you might come across Python functions which have the decorator @tf.function.

If you aren't sure what Python decorators do, read RealPython's guide on them.

But in short, decorators modify a function in one way or another.

In the @tf.function decorator case, it turns a Python function into a callable TensorFlow graph. Which is a fancy way of saying, if you've written your own Python function, and you decorate it with @tf.function, when you export your code (to potentially run on another device), TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).

For more on this, read the [Better performnace with tf.function guide](https://www.tensorflow.org/guide/function).

In [88]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [89]:

# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

If you noticed no difference between the above two functions (the decorated one and the non-decorated one) you'd be right.

Much of the difference happens behind the scenes. One of the main ones being potential code speed-ups where possible.

# 14. Finding access to GPUs
We've mentioned GPUs plenty of times throughout this notebook.

So how do you check if you've got one available?

You can check if you've got access to a GPU using `tf.config.list_physical_devices()`.

In [90]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

If the above outputs an empty array (or nothing), it means you don't have access to a GPU (or at least TensorFlow can't find it).

If you're running in Google Colab, you can access a GPU by going to Runtime -> Change Runtime Type -> Select GPU (note: after doing this your notebook will restart and any variables you've saved will be lost).

Once you've changed your runtime type, run the cell below.



In [92]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[]


You can also find information about your GPU using !nvidia-smi.

In [93]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.
